dist: bionic
language: go
go:
  - 1.14.2
services:
  - docker
env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
before_install:
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get install docker-ce docker-ce-cli containerd.io -y
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -u golang.org/x/lint/golint
jobs:
  include:
    #- stage: build_and_test
    #  script:
    #    - hack/verify-codegen.sh
    #    - hack/verify-boilerplate.sh
    #    - hack/verify-gofmt.sh
    #    - hack/verify-golint.sh
    #    - hack/verify-govet.sh
    #    - make fledged-amd64
    #    - make test
    #    - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - stage: release
      if: type = pull_request
      script:
        - travis_wait make GIT_BRANCH=${TRAVIS_BRANCH} release
