apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefledged-webhook-server
  namespace: kube-fledged
  labels:
    app: kubefledged
    kubefledged: kubefledged-webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      kubefledged: kubefledged-webhook-server
  template:
    metadata:
      labels:
        kubefledged: kubefledged-webhook-server
        app: kubefledged
    spec:
      initContainers:
      - image: senthilrch/kubefledged-webhook-server:v0.10.0
        command: ["/opt/bin/kubefledged-webhook-server"]
        args:
        - "--stderrthreshold=INFO"
        - "--init-server"
        imagePullPolicy: Always
        name: init
        env:
        - name: KUBEFLEDGED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_SERVER_SERVICE
          value: kubefledged-webhook-server
        - name: VALIDATING_WEBHOOK_CONFIG
          value: kubefledged-webhook-server
        - name: CERT_KEY_PATH
          value: "/var/run/secrets/webhook-server/"
        volumeMounts:
        - name: certkey-volume
          mountPath: "/var/run/secrets/webhook-server"
      containers:
      - image: senthilrch/kubefledged-webhook-server:v0.10.0
        command: ["/opt/bin/kubefledged-webhook-server"]
        args:
        - "--stderrthreshold=INFO"
        - "--cert-file=/var/run/secrets/webhook-server/tls.crt"
        - "--key-file=/var/run/secrets/webhook-server/tls.key"
        - "--port=443"
        imagePullPolicy: Always
        name: webhook-server
        env:
        - name: KUBEFLEDGED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: certkey-volume
          mountPath: "/var/run/secrets/webhook-server"
          readOnly: true
      volumes:
      - name: certkey-volume
        emptyDir: {}
      serviceAccountName: kubefledged-webhook-server
