apiVersion: charts.helm.k8s.io/v1alpha1
kind: KubeFledged
metadata:
  name: mykubefledged
  namespace: OPERATOR_NAMESPACE
spec:
  # Defaults defined in <project_dir>/helm-charts/kubefledged/values.yaml
  kubefledgedNameSpace: KUBEFLEDGED_NAMESPACE
