apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefledged-operator
  namespace: {{OPERATOR_NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubefledged-operator
  template:
    metadata:
      labels:
        name: kubefledged-operator
    spec:
      serviceAccountName: kubefledged-operator
      containers:
        - name: kubefledged-operator
          # Replace this with the built image name
          image: docker.io/senthilrch/kubefledged-operator:v0.8.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubefledged-operator"
