{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubefledged.clusterRoleBindingName" . }}
  labels:
{{ include "kubefledged.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubefledged.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubefledged.serviceAccountName" . }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
{{- end -}}
