{{- if .Values.webhookService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubefledged.fullname" . }}-webhook-server
  labels:
    {{ include "kubefledged.labels" . | nindent 4 }}
  namespace: {{ .Values.kubefledgedNameSpace }}
spec:
  ports:
  - name: webhook-server
    port: {{ .Values.webhookService.port }}
    protocol: TCP
    targetPort: {{ .Values.webhookService.targetPort }}
  selector:
    {{- include "kubefledged.selectorLabels" . | nindent 4 }}-webhook-server
  type: ClusterIP
{{- end -}}
