apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubefledged.webhookServiceName" . }}
  labels:
    {{ include "kubefledged.labels" . | nindent 4 }}
spec:
  ports:
  - name: webhook-server
    port: {{ .Values.webhookService.port }}
    protocol: TCP
    targetPort: {{ .Values.webhookService.targetPort }}
  selector:
    {{- include "kubefledged.selectorLabels" . | nindent 4 }}-webhook-server
  type: ClusterIP
