{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubefledged.serviceAccountName" . }}
  labels:
{{ include "kubefledged.labels" . | nindent 4 }}
{{- end -}}
